CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cor_hex VARCHAR(255),
    descricao VARCHAR(255)
);

CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    categoria_id BIGINT,
    tipo VARCHAR(255),
    recorrencia VARCHAR(255),
    dias_semana VARCHAR(255),
    hora_inicio TIME,
    duracao INTEGER,
    CONSTRAINT fk_tarefas_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);

CREATE TABLE ocorrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP,
    tarefa_id BIGINT,
    CONSTRAINT fk_ocorrencias_tarefa FOREIGN KEY (tarefa_id) REFERENCES tarefas(id)
);